# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='password')),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
