# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='chat.Chat'),
        ),
    ]
