# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=60),
        ),
    ]
