# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='FRlbLDKORSSwBxWOnNNeK4Ix7tjclEgyOvTQzBE9PCYBsumo4jgNiak5EM0W', max_length=60),
        ),
    ]
