# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171022_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='8peJjPU3pdwHauA56HSoNDNKvnwPxUeNxw7E3sUb8S9XyeWnKXXnP1XTU62B', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
