# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20171024_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='2jZGaOZBAQsCdpOJTIGWe5qvAAkxAnNRzhWDYGn159VQIcvxssczyedtqlgl', max_length=60),
        ),
    ]
