# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20171025_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='hhLF457ABYDDbxNV4MMOvVvfRJdnQjflE12XhMGArxG8jwrmOwWHj5SuAOE0', max_length=60),
        ),
    ]
