# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20171025_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='VmDBaorqGn17aVZ70PgbteEzltoxCVjB2opApgjnBbTVfLDfridWnS3AQoNJ', max_length=60),
        ),
    ]
