# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20171026_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='CwmOa8fX42ztDEJkeryKtjaHO0CIq7C0mdKOmHEEoPPr6hWkhIXh1aOqLT5T', max_length=60),
        ),
    ]
