# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singup',
            old_name='nickanem',
            new_name='nickname',
        ),
    ]
