# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singups', '0003_auto_20171005_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='password'),
        ),
    ]
